services:
  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: "0000"
      MYSQL_DATABASE: justart
      MYSQL_USER: root
      MYSQL_PASSWORD: "0000"
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://db:3306/justart
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: "0000"
    depends_on:
      - db
    networks:
      - app-network
    
    command: ./mvnw clean package -DskipTests

volumes:
  db_data:

networks:
  app-network:
